### ISSUE TITLE
"Kubernetes clusters should be accessible only over HTTPS" triggers false positive for ingresses configured with "appgw.ingress.kubernetes.io/appgw-ssl-certificate" annotation

### ISSUE THREAD

**Issue by abinet** [Azure/azure-policy#719]
#### Details of the scenario you tried and the problem that is occurring

False positive on policy "Kubernetes clusters should be accessible only over HTTPS" for ingress resources with ssl certificates configured per annotation "appgw.ingress.kubernetes.io/appgw-ssl-certificate".

```

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: default
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: azure/application-gateway
  name: myingress
spec:
  rules:
  - host: mydomain.example.org
    http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: 80
        path: /myservice/*
        pathType: ImplementationSpecific
```

#### Suggested solution to the issue

The described configuration is valid and should not be flagged by policy
