### ISSUE TITLE
   'IngressHttpsOnly: Policy should support “networking.k8s.io/v1" API'

### ISSUE THREAD

**Issue by ivanthelad** [Azure/azure-policy#959]
The policy checks the ingress rules and enforces HTTPS rules.

 The policy checks only the old ingress API format, the “networking.k8s.io/v1beta1”. This API group is deprecated in K8s 1.22 and replaced by the “networking.k8s.io/v1” where the ingress class definition is moved from the metadata.annotations to the spec.

**Comment by ivanthelad** [comment]
closing.  inspecting the rego expressions shows it does support the new api 
https://store.policy.core.windows.net/kubernetes/ingress-https-only/v1/template.yaml

**Comment by szasza576** [comment]
Indeed the ```re_match("^(extensions|networking.k8s.io)$", input.review.kind.group)``` matches to the new type as well but the following expressions ```violate_allow_http``` check the ```ingress.metadata.annotations["kubernetes.io/ingress.class"]```.

This annotation doesn't exist or isn't required in the new v1 API. As this field is not mandatory (it is replaced by spec.ingressClassName) hence if it is missing then the policy will mark any ingress rule as valid and doesn't check if TLS is configured.,

Here is an example ingress rule which bypasses the policy and creates a rule to HTTP:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing
  namespace: testingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: sample-service
            port:
              number: 80
```


And here is the kubectl printout after creation:
```
$> kubectl get ingress -n testingress
NAME      CLASS   HOSTS   ADDRESS       PORTS   AGE
testing   nginx   *       10.32.49.11   80      36s
```
